
version: 1

sources:
  - name: raw
    database: MODEL_DATA
    schema: MODEL_SCHEMA
    tables:
      - name: raw_orders
      - name: raw_customers

models:
  - name: stg_orders
    description: "Cleaned and transformed orders data"
    columns:
      - name: order_id
        tests:
          - not_null

  - name: stg_customers
    description: "Cleaned customer data without duplicates"
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique